
experiment_name: pretrained/phi2_GeoAware
downstream_task: pretraining
model_name: OVCompatible_FoundationModel4Task_nano   # **********************************
augmentations: True
batch_size: 16
model_device: cuda
generator_device: cuda
num_workers: 6
early_stop: 15
epochs: 50
input_channels: 8 # **********************************
output_channels: 3
input_size: 224 # **********************************
lr: 0.0001
lr_scheduler: cosine_annealing
n_shot: null
split_ratio: 1.0
regions: null
vis_val: True
warmup: True
warmp_steps: 5
warmup_gamma: null
min_lr: 0.000001
pretrained_model_path: null # **********************************
freeze_pretrained: False
data_path_128_10m: /home/phimultigpu/phisat2_foundation/lmdb_patches_256_1024
data_path_224_10m: /home/phimultigpu/phisat2_foundation/lmdb_patches_256_1024
data_path_224_30m: /home/phimultigpu/phisat2_foundation/lmdb_patches_256_1024
additional_inference: train_test                      # train_test, train_test_inference, inference, train_inference # **********************************
inference_model_path: null # **********************************
inference_also_on_trainval: False
data_path_inference_128: /home/phimultigpu/phisat2_foundation/lmdb_patches_256_1024 # **********************************
data_path_inference_224: /home/phimultigpu/phisat2_foundation/lmdb_patches_256_1024 # **********************************
output_path: /home/phimultigpu/phisat2_foundation/models
data_parallel: DDP
device_ids: [0, 1, 2, 3]
pad_to_10_bands: False
only_get_datasets: False
