
experiment_name: pretrained/phi2_GeoAware
model_name: phisatnet_nano   # **********************************
augmentations: True
batch_size: 16
model_device: cuda
generator_device: cuda
num_workers: 6
early_stop: 15
epochs: 50
input_channels: 8 # **********************************
output_channels: 3
input_size: 224 # **********************************
lr: 0.0001
lr_scheduler: cosine_annealing
n_shot: null
split_ratio: 1.0
regions: null
vis_val: True
warmup: True
warmup_steps: 5
warmup_gamma: null
min_lr: 0.000001
data_path: /home/phimultigpu/phisat2_foundation/lmdb_patches_256_1024
train_mode: train_test                      # train_test, train_test_inference, inference, train_inference # **********************************
output_path: /home/phimultigpu/phisat2_foundation/models
data_parallel: DDP
device_ids: [0, 1, 2, 3]
only_get_datasets: False
fixed_task: null