
experiment_name: pretrained/phi2_GeoAware
downstream_task: pretraining
model_name: OVCompatible_FoundationModel4Task_xsmall   # **********************************
augmentations: True
batch_size: 8
model_device: cuda
generator_device: cuda
num_workers: 6
early_stop: 15
epochs: 500
input_channels: 8 # **********************************
output_channels: 3
input_size: 224 # **********************************
lr: 0.00005
lr_scheduler: reduce_on_plateau
n_shot: null
split_ratio: 1.0
regions: null
vis_val: False
warmup: True
warmp_steps: 5
warmup_gamma: 10
pretrained_model_path: null # **********************************
freeze_pretrained: False
data_path_128_10m: /home/phimultigpu/phisat2_foundation/np_patches_128/
data_path_224_10m: /home/phimultigpu/phisat2_foundation/np_patches_256_ind/
data_path_224_30m: /home/phimultigpu/phisat2_foundation/np_patches_256_ind/
additional_inference: train_test                      # train_test, train_test_inference, inference, train_inference # **********************************
inference_model_path: null # **********************************
inference_also_on_trainval: False
data_path_inference_128: /home/phimultigpu/phisat2_foundation/np_patches_128/ # **********************************
data_path_inference_224: /home/phimultigpu/phisat2_foundation/np_patches_256_ind/ # **********************************
output_path: /home/phimultigpu/phisat2_foundation/models
data_parallel: DDP
device_ids: [1, 3]
pad_to_10_bands: False
only_get_datasets: False
