
experiment_name: nshot_phi2/phi2_GeoAware
downstream_task: building
model_name: GeoAware_mh_pred_core_nano
augmentations: True
batch_size: 64
model_device: cuda
generator_device: cuda
num_workers: 16
early_stop: 15
epochs: 500
input_channels: 10
output_channels: 1
input_size: 128
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot: 0
split_ratio: null
regions: null
vis_val: True
warmup: True
warmp_steps: 5
warmup_gamma: 10
min_lr: null
pretrained_model_path: /home/phisat2/pretrained_weights/CoreEncoderMultiHead_geo_pred_best.pt
freeze_pretrained: True
data_path_128_10m: /Data_phisat2/np_patches_128/
data_path_224_10m: null
data_path_224_30m: null
train_mode: train_test                      # train_test, train_test_inference, inference, train_inference
downstream_model_path: null
data_path_inference_128: /Data_phisat2/np_patches_128/
data_path_inference_224: null
output_path: /home/phisat2/models
data_parallel: False
device_ids: [0]
pad_to_10_bands: True # required for models trained with 10 bands (all but phisatnet)
only_get_datasets: False
